# Cloudflare Pages Configuration
[build]
  command = "./build.sh"
  publish = "out"

[build.environment]
  NODE_VERSION = "20.9.0"

# Asset exclusions (files that shouldn't be uploaded)
[build.upload]
  exclude = [
    ".next/cache/**",
    ".next/cache",
    "**/*.pack"
  ] 