# Direct Cloudflare Pages configuration
# This overrides all other configuration files

[build]
command = "./build.sh"
output_directory = "out"

[build.environment]
NODE_VERSION = "20.9.0"
NEXT_TELEMETRY_DISABLED = "1"

# Asset exclusions (files that shouldn't be uploaded)
[build.upload]
  exclude = [
    ".next/cache/**",
    ".next/cache",
    "**/*.pack"
  ] 