name = "rezigco-landing-page"
type = "webpack"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[site]
bucket = "./out"
entry-point = "./.cloudflare/workers-site"

[build]
command = "npm run build:cf"

# Asset exclusions (files that shouldn't be uploaded)
[build.upload]
format = "service-worker"
exclude = [".next/cache/**", ".next/cache", "**/*.pack"]

[env.production]
route = "" 